export const routes = {
  home: "/",
  valheimOne: "/valheim-1-0",
  deepNorth: "/deep-north",
  updates: "/updates",
  servers: "/servers",
  dedicatedServerSetup: "/servers/dedicated-server-setup",
  updatingServer: "/servers/updating-a-server",
  existingOrNewWorld: "/servers/existing-world-vs-new-world",
  worldBackupRestore: "/servers/world-backup-restore",
  moveLocalWorld: "/servers/move-local-world-to-server",
  crossplay: "/servers/crossplay",
  serverNotShowing: "/servers/server-not-showing",
  serverRequirements: "/servers/server-requirements",
  serverSettings: "/servers/server-settings",
  serverHosting: "/servers/best-server-hosting",
  world: "/world",
  regionMeadows: "/world/regions/meadows",
  regionBlackForest: "/world/regions/black-forest",
  regionSwamp: "/world/regions/swamp",
  regionMountain: "/world/regions/mountain",
  regionPlains: "/world/regions/plains",
  regionMistlands: "/world/regions/mistlands",
  regionAshlands: "/world/regions/ashlands",
  bosses: "/bosses",
  bossEikthyr: "/bosses/eikthyr",
  bossTheElder: "/bosses/the-elder",
  bossBonemass: "/bosses/bonemass",
  bossModer: "/bosses/moder",
  bossYagluth: "/bosses/yagluth",
  bossTheQueen: "/bosses/the-queen",
  bossFader: "/bosses/fader",
  about: "/about",
  contact: "/contact",
  dataSources: "/data-sources",
  editorialPolicy: "/editorial-policy",
  privacy: "/privacy",
  terms: "/terms",
} as const;

export type RoutePath = (typeof routes)[keyof typeof routes];

